INSERT INTO GROUP_(ID, NAME_GROUP) VALUES (1, 'ВМ-31');
INSERT INTO GROUP_(ID, NAME_GROUP) VALUES (2, 'ИС-31');

INSERT INTO CATHEDRA(ID, NAME_CATHEDRA) VALUES(1, 'ВММКС');
INSERT INTO CATHEDRA(ID, NAME_CATHEDRA) VALUES(2, 'МиИ');

INSERT INTO PROFESSOR(ID, CATHEDRA_ID, NAME_PROFESSOR) VALUES (1, 1, 'Яшин А.Д.');
INSERT INTO PROFESSOR(ID, CATHEDRA_ID, NAME_PROFESSOR) VALUES (2, 2, 'Головизин В.В.');
INSERT INTO PROFESSOR(ID, CATHEDRA_ID, NAME_PROFESSOR) VALUES (3, 2, 'Родионова А.Г.');

INSERT INTO SUBJECT(ID, PROFESSOR_ID, NAME_SUBJECT) VALUES(1, 3, 'Мат.Ан.');
INSERT INTO SUBJECT(ID, PROFESSOR_ID, NAME_SUBJECT) VALUES(2, 2, 'Алгебра и Геометрия');
INSERT INTO SUBJECT(ID, PROFESSOR_ID, NAME_SUBJECT) VALUES(3, 1, 'Логика');

INSERT INTO GROUP_SUBJECT(ID, SUBJECT_ID, GROUP_ID) VALUES (1, 1, 1);
INSERT INTO GROUP_SUBJECT(ID, SUBJECT_ID, GROUP_ID) VALUES (2, 2, 2);
INSERT INTO GROUP_SUBJECT(ID, SUBJECT_ID, GROUP_ID) VALUES (3, 2, 1);
INSERT INTO GROUP_SUBJECT(ID, SUBJECT_ID, GROUP_ID) VALUES (4, 3, 1);

insert into STUDENT(ID, FIRST_NAME, SECOND_NAME, GROUP_ID) values(1,'Васька', 'Пупкин', 1);
insert into STUDENT(ID, FIRST_NAME, SECOND_NAME, GROUP_ID) values(2,'Петька', 'Кеплер', 2);
insert into STUDENT(ID, FIRST_NAME, SECOND_NAME, GROUP_ID) values(3,'Евпатий', 'Гофман', 1);

